format_version: 2
pipelines:
    pipeline-name:
        group: group-name
        materials:
            git-repo:
                git: https://github.com/ampharino/vue-gotham-todo.git
                branch: master
        stages:
            - first-stage:
                  jobs:
                      list:
                          tasks:
                              - exec:
                                    command: ls
                                    arguments:
                                        - .

    Todo-app:
        group: todo-app
        materials:
            git-repo:
                git: https://github.com/ampharino/vue-gotham-todo.git
                branch: master
        stages:
            - build:
                  jobs:
                      build:
                          tasks:
                              - exec:
                                    command: bash
                                    arguments: ./build.sh

                              - exec:
                                    command: bash
                                    arguments: ./apply-infrastructure.sh
